// <auto-generated />
using System;
using Korean_Convenience_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korean_Convenience_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916013839_Prueba")]
    partial class Prueba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korean_Convenience_Store.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockSeguridad")
                        .HasColumnType("integer");

                    b.Property<string>("TipoCobro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Categoria = "Fideos",
                            Nombre = "Ramen Samyang 140g",
                            PrecioVenta = 8.50m,
                            StockActual = 20,
                            StockSeguridad = 5,
                            TipoCobro = "Unidad"
                        },
                        new
                        {
                            Id = 101,
                            Categoria = "Bebidas",
                            Nombre = "Bebida Milkis 250ml",
                            PrecioVenta = 6.00m,
                            StockActual = 15,
                            StockSeguridad = 5,
                            TipoCobro = "Unidad"
                        },
                        new
                        {
                            Id = 102,
                            Categoria = "Snacks",
                            Nombre = "Snack Pocky Chocolate",
                            PrecioVenta = 5.50m,
                            StockActual = 25,
                            StockSeguridad = 5,
                            TipoCobro = "Unidad"
                        },
                        new
                        {
                            Id = 103,
                            Categoria = "Caldos",
                            Nombre = "Tteokbokki Picante",
                            PrecioVenta = 12.00m,
                            StockActual = 10,
                            StockSeguridad = 3,
                            TipoCobro = "Unidad"
                        },
                        new
                        {
                            Id = 104,
                            Categoria = "Bebidas",
                            Nombre = "Soju Original 360ml",
                            PrecioVenta = 18.00m,
                            StockActual = 8,
                            StockSeguridad = 2,
                            TipoCobro = "Unidad"
                        });
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@bekeenco.com",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "Kim Joung",
                            PasswordHash = "AQAAAAIAAYagAAAAEAy+TwyNxBP60uI529mx6i7VYumar2q1oIHcjrrE1pJVUzQ+fLTPYMtXBhbmfkjsDg==",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "cajero@bekeenco.com",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreUsuario = "Cajero BekeenCo",
                            PasswordHash = "AQAAAAIAAYagAAAAEJArxw5RUh1ystd/aQfkZ840AwGNGfAJBcAOSeT3bv1CZhoyFsqyvC+2sgajyjPqEg==",
                            Rol = "Cajero"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
