// <auto-generated />
using System;
using Korean_Convenience_Store.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korean_Convenience_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korean_Convenience_Store.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_carrito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadGramo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("CantidadGramo");

                    b.Property<int>("CantidadUnitario")
                        .HasColumnType("integer")
                        .HasColumnName("CantidadUnitario");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_producto");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("Id_user");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUser");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadOGramos")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cantidad_o_gramos");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("integer")
                        .HasColumnName("Id_venta");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio_aplicado");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("Id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio_unitario");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Stock_actual");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Stock_minimo");

                    b.Property<string>("TipoVenta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Tipo_venta");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_producto");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("Id_user");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUser");

                    b.ToTable("Resenas", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@bekeenco.com",
                            NombreUsuario = "Kim Joung",
                            PasswordHash = "AQAAAAIAAYagAAAAEDRcR/4rK00i72xa9wLi4kH83WAexWl4n7pHLT3pnq+rHIX9a7/2IwK9UEFDA2aGcw==",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "cajero@bekeenco.com",
                            NombreUsuario = "Cajero BekeenCo",
                            PasswordHash = "AQAAAAIAAYagAAAAEHqqoQrUxV3xn6fhX+xjq9tBfjEOCYQUmC+WYFHWEH25UTq77OOMHhAbHzlqMTmJUQ==",
                            Rol = "Cajero"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "cliente@bekeenco.com",
                            NombreUsuario = "Cliente Kiosco",
                            PasswordHash = "AQAAAAIAAYagAAAAEM/IZdSOmRZsmv4VyEZW1IUUhTbn5gTzr49zwlAzPRGXO/LdPFNejHVLfbCMf1nIXw==",
                            Rol = "Cliente"
                        });
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_venta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha_venta");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("Id_user");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Metodo_pago");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Carrito", b =>
                {
                    b.HasOne("Korean_Convenience_Store.Models.Producto", "Producto")
                        .WithMany("Carritos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Korean_Convenience_Store.Models.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.DetalleVenta", b =>
                {
                    b.HasOne("Korean_Convenience_Store.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Korean_Convenience_Store.Models.Venta", "Venta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Producto", b =>
                {
                    b.HasOne("Korean_Convenience_Store.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Resena", b =>
                {
                    b.HasOne("Korean_Convenience_Store.Models.Producto", "Producto")
                        .WithMany("Resenas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Korean_Convenience_Store.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Venta", b =>
                {
                    b.HasOne("Korean_Convenience_Store.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetallesVenta");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Resenas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Korean_Convenience_Store.Models.Venta", b =>
                {
                    b.Navigation("DetallesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
