// <auto-generated />
using System;
using KoreanStoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KoreanStoreApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KoreanStoreApi.Models.Carrito", b =>
                {
                    b.Property<int>("Id_carrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_carrito"));

                    b.Property<decimal>("CantidadGramo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CantidadUnitario")
                        .HasColumnType("integer");

                    b.Property<int>("Id_producto")
                        .HasColumnType("integer");

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_carrito");

                    b.HasIndex("Id_producto");

                    b.HasIndex("Id_user");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_detalle"));

                    b.Property<decimal>("Cantidad_o_gramos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Id_producto")
                        .HasColumnType("integer");

                    b.Property<int>("Id_venta")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio_aplicado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_detalle");

                    b.HasIndex("Id_producto");

                    b.HasIndex("Id_venta");

                    b.ToTable("DetallesVenta");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Producto", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_producto"));

                    b.Property<int>("Id_proveedor")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio_unitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stock_actual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stock_minimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo_venta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_producto");

                    b.HasIndex("Id_proveedor");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_producto")
                        .HasColumnType("integer");

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_producto");

                    b.HasIndex("Id_user");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@bekeenco.com",
                            NombreUsuario = "Kim Joung",
                            PasswordHash = "AQAAAAIAAYagAAAAEM8EaO0Rg8e9Raib7pv4VCLrxLKSKicMTiyT/+YyEJa79ZhZNBknB2bvte8V+5J7Gg==",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "cajero@bekeenco.com",
                            NombreUsuario = "Cajero BekeenCo",
                            PasswordHash = "AQAAAAIAAYagAAAAEInWBP1K0riknXa78mSa5Pq+3M4kPx1xjBfezYwwOqXDT1DtJwQRxa5a4xILfKMRLQ==",
                            Rol = "CajeroVendedor"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "cliente@bekeenco.com",
                            NombreUsuario = "Cliente Demo",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJQ8cHjxX6wCKEg9NSsJXhEylzfn9WEdMp39BSDv///Y/WK0W9zn1iAt+T0NlKfIA==",
                            Rol = "Cliente"
                        });
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Venta", b =>
                {
                    b.Property<int>("Id_venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_venta"));

                    b.Property<DateTime>("Fecha_venta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_user")
                        .HasColumnType("integer");

                    b.Property<string>("Metodo_pago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_venta");

                    b.HasIndex("Id_user");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Carrito", b =>
                {
                    b.HasOne("KoreanStoreApi.Models.Producto", "Producto")
                        .WithMany("Carritos")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoreanStoreApi.Models.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.DetalleVenta", b =>
                {
                    b.HasOne("KoreanStoreApi.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KoreanStoreApi.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Producto", b =>
                {
                    b.HasOne("KoreanStoreApi.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Reseña", b =>
                {
                    b.HasOne("KoreanStoreApi.Models.Producto", "Producto")
                        .WithMany("Reseñas")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoreanStoreApi.Models.Usuario", "Usuario")
                        .WithMany("Reseñas")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Venta", b =>
                {
                    b.HasOne("KoreanStoreApi.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetallesVenta");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Reseñas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("KoreanStoreApi.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
